import { render, screen, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { StarsChartCard } from "./StarsChartCard";
import { useTrackedRepoView } from "../../tracked-repos/useTrackedRepoView/useTrackedRepoView";

vi.mock("../../tracked-repos/useTrackedRepoView/useTrackedRepoView", () => ({
  useTrackedRepoView: vi.fn(),
}));
const mockedUseTrackedRepoView = vi.mocked(useTrackedRepoView);

function baseView(overrides: Partial<ReturnType<typeof useTrackedRepoView>> = {}) {
  return {
    trackedFullNames: [],
    entryByFullName: new Map(),
    sortKey: "stars",
    setSortKey: vi.fn(),
    filters: {},
    setFilters: vi.fn(),
    clearFilters: vi.fn(),
    hasActiveFilters: false,
    maxStarBound: 1000,
    sortedFullNames: [],
    ...overrides,
  } as ReturnType<typeof useTrackedRepoView>;
}

// React's useId() ids are based on how many roots have mounted earlier in the
// process, so they shift depending on which other tests ran first. Normalize
// them so the snapshot doesn't depend on execution order.
function normalizeAutoGeneratedIds(container: HTMLElement) {
  const idMap = new Map<string, string>();
  let counter = 0;
  container.querySelectorAll("[id]").forEach((el) => {
    const id = el.getAttribute("id");
    if (id?.startsWith("_r_")) {
      const stableId = `stable-id-${counter++}`;
      idMap.set(id, stableId);
      el.setAttribute("id", stableId);
    }
  });
  container.querySelectorAll("[clip-path]").forEach((el) => {
    const match = el.getAttribute("clip-path")?.match(/^url\(#(.+)\)$/);
    const referencedId = match?.[1];
    if (referencedId && idMap.has(referencedId)) {
      el.setAttribute("clip-path", `url(#${idMap.get(referencedId)})`);
    }
  });
}

describe("StarsChartCard", () => {
  it("renders nothing when no tracked repo has loaded data yet", () => {
    mockedUseTrackedRepoView.mockReturnValue(baseView({ sortedFullNames: ["a/a"] }));
    const { container } = render(<StarsChartCard />);
    expect(container).toBeEmptyDOMElement();
  });

  it("shows a chart skeleton while the chart chunk loads, then swaps in the real chart", async () => {
    const entryByFullName = new Map([
      ["a/a", { fullName: "a/a", data: { fullName: "a/a", stargazersCount: 10 } }],
    ]);
    mockedUseTrackedRepoView.mockReturnValue(
      baseView({ sortedFullNames: ["a/a"], entryByFullName } as never),
    );
    const { container } = render(<StarsChartCard skipAnimation />);

    expect(container.querySelectorAll(".MuiSkeleton-root").length).toBeGreaterThan(0);

    // Waits on a real dynamic import resolving (the @mui/x-charts chunk) plus
    // a React re-render, not just a fixed delay - the default 1000ms window
    // is occasionally too short under load (e.g. the full suite running
    // concurrently), so this needs a longer budget to stay non-flaky.
    await waitFor(
      () => {
        expect(container.querySelector(".MuiBarElement-root")).toBeInTheDocument();
      },
      { timeout: 5000 },
    );
    expect(container.querySelectorAll(".MuiSkeleton-root").length).toBe(0);
  });

  it("renders the chart with loaded repos, no notice when all have loaded", () => {
    const entryByFullName = new Map([
      ["a/a", { fullName: "a/a", data: { fullName: "a/a", stargazersCount: 10 } }],
    ]);
    mockedUseTrackedRepoView.mockReturnValue(
      baseView({ sortedFullNames: ["a/a"], entryByFullName } as never),
    );
    render(<StarsChartCard />);

    expect(screen.getByText("Stars by repo")).toBeInTheDocument();
    expect(screen.queryByRole("status")).toBeNull();
  });

  it("shows a partial-data notice when some tracked repos haven't loaded", () => {
    const entryByFullName = new Map([
      ["a/a", { fullName: "a/a", data: { fullName: "a/a", stargazersCount: 10 } }],
    ]);
    mockedUseTrackedRepoView.mockReturnValue(
      baseView({ sortedFullNames: ["a/a", "b/b"], entryByFullName } as never),
    );
    render(<StarsChartCard />);

    expect(screen.getByRole("status")).toHaveTextContent("Showing 1 of 2 tracked repos");
  });

  it("matches its snapshot", async () => {
    const entryByFullName = new Map([
      ["a/a", { fullName: "a/a", data: { fullName: "a/a", stargazersCount: 10 } }],
    ]);
    mockedUseTrackedRepoView.mockReturnValue(
      baseView({ sortedFullNames: ["a/a"], entryByFullName } as never),
    );
    const { container } = render(<StarsChartCard skipAnimation />);

    // Bar heights come from an async layout pass (ResizeObserver-driven), so
    // even with skipAnimation the first paint can still be pre-layout (all
    // bars at 0 height). Wait for that pass to settle before snapshotting,
    // or the snapshot becomes dependent on how much prior test activity had
    // already primed layout timing.
    await waitFor(
      () => {
        const bar = container.querySelector(".MuiBarElement-root");
        expect(bar).not.toHaveStyle({ height: "0px" });
      },
      { timeout: 5000 },
    );

    normalizeAutoGeneratedIds(container);
    expect(container).toMatchSnapshot();
  });
});
